### ISSUE TITLE
Roms Crashing on the Nintendo Switch HW / Emulator 

### ISSUE THREAD

**Issue by natehaxx** [ekeeke/Genesis-Plus-GX#215]
Well i dont own IDA to Check the Crash Codes but maybe its helpful to figure out why Genesis GX wont load any roms on the Switch or Ryujinx , i can try to load md files it crashes it also crashes with 32x files.

`Unhandled Exception: ChocolArm64.Exceptions.VmmPageFaultException: Tried to access unmapped address 0x0000000000000000!
   at ChocolArm64.Memory.AMemory.EnsureAccessIsValid(Int64 Position, AMemoryPerm Perm) in /Users/DJAlexDaCosta/Ryujinx/ChocolArm64/Memory/AMemory.cs:line 442
   at Sub0000000008227408(AThreadState , AMemory , UInt64 , UInt64 )
   at ChocolArm64.ATranslator.ExecuteSubroutine(AThread Thread, Int64 Position) in /Users/DJAlexDaCosta/Ryujinx/ChocolArm64/ATranslator.cs:line 65
   at ChocolArm64.AThread.<Execute>b__18_0() in /Users/DJAlexDaCosta/Ryujinx/ChocolArm64/AThread.cs:line 45
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)`

i was the last days trying to get it to work on my device , modiyfing the makefile and grabbing some logs to see where the issue is 

, but Threading could be also an issue why the games wont load

**Comment by ekeeke** [comment]
I don't maintain the Switch port and it's obviously a port specific issue, not an emulator issue so you wil have to see with the people behind that port.

From the look of that log, the crash does not occur in Genesis Plus GX code and is caused by trying to access a NULL pointer.

**Comment by natehaxx** [comment]
thanks ekeeke that might me help solve the issue
